language: php
php: 7.1

env:
  global:
    - APP_ENV=prod
    - APP_SECRET=na
    - DATABASE_URL=na
    - MAILER_HOST=na
    - MAILER_USERNAME=na
    - MAILER_PASSWORD=na
    - DB_WRITE_HOST=na
    - DB_PORT=na
    - DB_NAME=na
    - DB_WRITE_USER=na
    - DB_WRITE_PASSWORD=na
    - APP_CAPTCHA_SECRET=na
    - APP_REQUEST_FROM_ADDRESS=na
    - APP_REQUEST_TO_ADDRESS=na
    - ADMIN_PASSWORD=na

cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.yarn-cache"
  - vendor

before_install:
  - source ~/.nvm/nvm.sh && nvm install 10 && nvm use 10
  - export PATH=$HOME/.yarn/bin:$PATH && travis_retry curl -o- -L https://yarnpkg.com/install.sh
    | bash

install:
  - cd app/
  - composer install --no-interaction
  - cd ../static
  - yarn install
  - cd ../

script:
  - cd app/
  - composer cs
  - composer stan
  - composer test
  - cd ../static
  - yarn client
  - cd ../

after_success:
  - cd app/
  - composer install --no-interaction --no-dev --optimize-autoloader
  - cd ../static
  - yarn install --production --ignore-scripts --prefer-offline
  - cd ../

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name $GITHUB_USERNAME
  - git config --local user.email $GITHUB_EMAIL
  - git tag "$(date +'%Y%m%d%H%M%S')"
  # zip up the application
  - cd app
  - tar -cf ../sohba.tar config public src templates vendor composer.json

deploy:
  # GitHub - Add zip to release
  - provider: releases
    api_key:
      secure: $GITHUB_KEY
    file: sohba.tar
    skip_cleanup: true
