jobs:
  include:
    - stage: build
      script: skip
      language: php
      php: 7.1
      env:
        - APP_ENV=prod
        - APP_SECRET=na
        - DATABASE_URL=na
        - MAILER_HOST=na
        - MAILER_USERNAME=na
        - MAILER_PASSWORD=na
        - DB_WRITE_HOST=na
        - DB_PORT=na
        - DB_NAME=na
        - DB_WRITE_USER=na
        - DB_WRITE_PASSWORD=na
        - APP_CAPTCHA_SECRET=na
        - APP_REQUEST_FROM_ADDRESS=na
        - APP_REQUEST_TO_ADDRESS=na
        - ADMIN_PASSWORD=na
      before_install:
        - cd app

      install:
        - composer install --no-interaction

      script:
        - composer cs
        - composer stan
        - composer test

      after_success:
        - composer install --no-interaction --no-dev --optimize-autoloader
        - php bin/console cache:clear
        - php bin/console cache:warmup

    - stage: build
      script: skip
      language: node_js
      node_js:
        - "10"
      cache:
        yarn: true
      before_install:
        - cd static
      script:
        - yarn install
        - yarn client
      after_success:
        - yarn install --production --ignore-scripts --prefer-offline

    - stage: deploy
      script: skip
      before_deploy:
        # Set up git user name and tag this commit
        - git config --local user.name $GITHUB_USERNAME
        - git config --local user.email $GITHUB_EMAIL
        - git tag "$(date +'%Y%m%d%H%M%S')"
        # zip up the application
        - tar -cf sohba.tar app/config app/public app/src app/templates app/vendor app/var app/composer.json public_html/static
      deploy:
        # GitHub - Add zip to release
        - provider: releases
          api_key:
            secure: $GITHUB_KEY
          file: sohba.tar
          skip_cleanup: true

stages:
  - php
  - node
  - name: deploy
    if: branch = master
