branches:
  only:
  - master

matrix:
  include:
    - language: php
      php: 7.1
      env:
        - APP_ENV=prod
      before_install:
        - cd app

      install:
        - composer install --no-interaction

      script:
        - composer cs
        - composer stan
        - composer test

      after_success:
        - composer install --no-interaction --no-dev --optimize-autoloader
        - php bin/console cache:clear
        - php bin/console cache:warmup

    - language: node_js
      node_js:
        - "10"
      cache:
        yarn: true
      before_install:
        - cd static
      script:
        - yarn install
        - yarn test
        - yarn client
      after_success:
        - yarn install --production --ignore-scripts --prefer-offline

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name $GITHUB_USERNAME
  - git config --local user.email $GITHUB_EMAIL
  - git tag "$(date +'%Y%m%d%H%M%S')"
  # zip up the application
  - tar -cf sohba.tar config public src templates vendor var composer.json public_html/static

deploy:
  # GitHub - Add zip to release
  - provider: releases
    api_key:
      secure: $GITHUB_KEY
    file: sohba.tar
    skip_cleanup: true
