# docker-compose file for local dev only
version: "3"

services:
  sohba:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html

  sohba-db:
    restart: always
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sohbaorg_sohba
    ports:
      - "3306:3306"
    volumes:
      - sohbamysql-data:/var/lib/sohbamysql

  sohba-node:
    image: kkarczmarczyk/node-yarn:latest
    volumes:
      - .:/var/www
    working_dir: /var/www/static

volumes:
  sohbamysql-data:
