security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: plaintext
    providers:
        in_memory_users:
            memory:
                users:
                    - identifier: 'admin'
                      password: '%env(ADMIN_PASSWORD)%'
                      roles: [ ROLE_ADMIN ]
    firewalls:
        main:
            pattern: ^/
            http_basic: ~
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
