name: Build Application

on: [push, pull_request]

jobs:
  php:
    defaults:
      run:
        working-directory: app
    env:
      APP_ENV: prod
      APP_SECRET: na
      DATABASE_URL: na
      MAILER_HOST: na
      MAILER_USERNAME: na
      MAILER_PASSWORD: na
      DB_WRITE_HOST: na
      DB_PORT: na
      DB_NAME: na
      DB_WRITE_USER: na
      DB_WRITE_PASSWORD: na
      APP_CAPTCHA_SECRET: na
      APP_REQUEST_FROM_ADDRESS: na
      APP_REQUEST_TO_ADDRESS: na
      ADMIN_PASSWORD: na
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Run test suite
        run: composer run test

      - name: PHPStan
        run: composer run stan

      - name: CodeStyle
        run: composer run cs

      - name: Install Prod  dependencies
        run: composer install --prefer-dist --no-interaction --no-dev --optimize-autoloader

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: php-app
          retention-days: 1
          path: |
            config/
            public/
            src/
            templates/
            vendor/
            composer.json

  javascript:
    defaults:
      run:
        working-directory: static
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn client

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: js-app
          path: ../app/static/
          retention-days: 1

  deploy:
    needs: [php, javascript]
    defaults:
      run:
        working-directory: app

    runs-on: ubuntu-latest
    steps:
      - name: Get files
        uses: actions/download-artifact@v2
      - name: List files
        run: |
          pwd
          ls .
          ls public
          ls public/static
#      - name: Zip
#        run: tar -cf ../sohba.tar config public src templates vendor composer.json


#  - name: Deploy
#    if: github.ref == 'refs/heads/master'
#    run: curl ${{ secrets.ENVOYER_HOOK }}?sha=${{ github.sha }}
