name: PHP Composer

on: [push, pull_request]

env:
  APP_ENV: prod
  APP_SECRET: na
  DATABASE_URL: na
  MAILER_HOST: na
  MAILER_USERNAME: na
  MAILER_PASSWORD: na
  DB_WRITE_HOST: na
  DB_PORT: na
  DB_NAME: na
  DB_WRITE_USER: na
  DB_WRITE_PASSWORD: na
  APP_CAPTCHA_SECRET: na
  APP_REQUEST_FROM_ADDRESS: na
  APP_REQUEST_TO_ADDRESS: na
  ADMIN_PASSWORD: na

defaults:
  run:
    working-directory: app

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        phpVersion:
          - 7.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Setup PHP
        uses: php-actions/composer@v4
        with:
          php_version: ${{ matrix.phpVersion }}
          args: --prefer-dist --no-interaction --no-suggest

      - name: Run test suite
        uses: php-actions/composer@v4
        with:
          php_version: ${{ matrix.phpVersion }}
          command: run test

      - name: PHPStan
        uses: php-actions/composer@v5
        with:
          php_version: ${{ matrix.phpVersion }}
          command: run stan

      - name: CodeStyle
        uses: php-actions/composer@v4
        with:
          php_version: ${{ matrix.phpVersion }}
          command: run cs

      - name: Install Prod  dependencies
        uses: php-actions/composer@v4
        with:
          php_version: ${{ matrix.phpVersion }}
          dev: no
          args: --no-interaction --no-dev --optimize-autoloader

#  - name: Deploy
#    if: github.ref == 'refs/heads/master'
#    run: curl ${{ secrets.ENVOYER_HOOK }}?sha=${{ github.sha }}