name: PHP Composer

on: [push, pull_request]

env:
  APP_ENV: prod
  APP_SECRET: na
  DATABASE_URL: na
  MAILER_HOST: na
  MAILER_USERNAME: na
  MAILER_PASSWORD: na
  DB_WRITE_HOST: na
  DB_PORT: na
  DB_NAME: na
  DB_WRITE_USER: na
  DB_WRITE_PASSWORD: na
  APP_CAPTCHA_SECRET: na
  APP_REQUEST_FROM_ADDRESS: na
  APP_REQUEST_TO_ADDRESS: na
  ADMIN_PASSWORD: na

defaults:
  run:
    working-directory: app

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: php-actions/composer@v5
        with:
          php_version: 7.4
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-suggest
      - name: Run test suite
        run: |
          composer run-script cs
          composer run-script stan
          composer run-script test
  build:
    needs: [ test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: php-actions/composer@v5
        with:
          php_version: 7.4
      - name: Install Prod Composer dependencies
        run: composer install --no-interaction --no-dev --optimize-autoloader
