name: PHP Composer

on: [push, pull_request]

jobs:
  build:
    defaults:
      run:
        working-directory: app

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-suggest
      - name: Run test suite
        run: |
          composer run-script cs
          composer run-script stan
          composer run-script test
