name: PHP Composer

on: [push, pull_request]

env:
  APP_ENV: prod
  APP_SECRET: na
  DATABASE_URL: na
  MAILER_HOST: na
  MAILER_USERNAME: na
  MAILER_PASSWORD: na
  DB_WRITE_HOST: na
  DB_PORT: na
  DB_NAME: na
  DB_WRITE_USER: na
  DB_WRITE_PASSWORD: na
  APP_CAPTCHA_SECRET: na
  APP_REQUEST_FROM_ADDRESS: na
  APP_REQUEST_TO_ADDRESS: na
  ADMIN_PASSWORD: na

defaults:
  run:
    working-directory: app

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Run test suite
        run: composer run test

      - name: PHPStan
        run: composer run stan

      - name: CodeStyle
        run: composer run cs

      - name: Install Prod  dependencies
        run: composer install --prefer-dist --no-interaction --no-dev --optimize-autoloader

#  - name: Deploy
#    if: github.ref == 'refs/heads/master'
#    run: curl ${{ secrets.ENVOYER_HOOK }}?sha=${{ github.sha }}
